name: PR title check
on:
  pull_request:
    branches: [ "main" ]
    types: ["edited", "opened"]
  workflow_dispatch:
    inputs:
      dryrun:
        description: 'dry-run?(true/false)'
        required: true
        default: 'false'
jobs:
  titlecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - if: github.event.inputs.dryrun == 'true'
        run: |
          echo "Working"

