name: PR title check
on:
  pull_request:
    branches: [ "main" ]
    types: ["edited", "opened"]
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'dry-run?(true/false)'
        required: true
        default: 'false'
jobs:
  titlecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: "(fix|feat).*"
          helpMessage: "Example: 'feat: example of title'"

